import {OPTIONAL_RULES} from "../module/combat/optional/settings.mjs";
import {recordShot} from "../module/combat/optional/runtime.mjs";
import {repairWeapon} from "../module/combat/optional/repairs.mjs";
import {addWound} from "../module/combat/optional/wounds.mjs";
import {stateOf} from "../module/combat/state.mjs";
const NS="paranoia-2-edition",check=(v,message)=>{if(!v)throw Error(message);};
export async function runOptionalChecks(){
  check((game.world.id==="society-fresh-validation"||game.world.id.startsWith("release-audit-"))&&game.user.isGM,"Requires isolated World and GM");
  const set=async(...keys)=>{await game.settings.set(NS,"useOptionalCombatRules",true);for(const key of Object.keys(OPTIONAL_RULES))await game.settings.set(NS,`optionalCombat.${key}`,keys.includes(key));};
  const actors=await Actor.createDocuments(["OPT-A","OPT-B","OPT-C","OPT-D"].map(name=>({name,type:"character",system:{identity:{name,sector:"TEST"},securityClearance:"red",mutantPower:{points:{value:0,max:0}},skills:{dexterity:{laserWeapons:{value:14}},mechanicalTalent:{systemsEngineering:{value:20}}}}})));
  const [a,b,c,d]=actors;const [bWeapon]=await b.createEmbeddedDocuments("Item",[{name:"Surprised defender weapon",type:"weapon",system:{weaponCategory:"laser",skill:"dexterity.laserWeapons"}}]);
  const createdItems=await a.createEmbeddedDocuments("Item",[{name:"Optional test laser",type:"weapon",flags:{[NS]:{catalogId:"laser-pistol"}},system:{weaponCategory:"laser",skill:"dexterity.laserWeapons",burstCapable:true,requiredArm:"right",ammoCurrent:6,ammunition:{capacity:6},ammoType:"laser-charge",maxRangeMeters:50,repairSkill:"mechanicalTalent.systemsEngineering"}},{name:"Optional spare charge",type:"equipment",flags:{[NS]:{catalogId:"laser-charge"}},system:{quantity:2,securityClearance:"red"}},{name:"Poly armor",type:"armor",system:{equipped:true,protectionType:"laser",protectionValue:4,protections:[{type:"laser",value:4},{type:"melee",value:3},{type:"projectile",value:2},{type:"piercingProjectile",value:6}]}}]);
  const weapon=createdItems.find(i=>i.type==="weapon"),ammo=createdItems.find(i=>i.type==="equipment"),armor=createdItems.find(i=>i.type==="armor");
  const combat=await Combat.create({combatants:actors.map(actor=>({actorId:actor.id,name:actor.name}))});const ca=combat.combatants.find(p=>p.actor.id===a.id),cb=combat.combatants.find(p=>p.actor.id===b.id),cc=combat.combatants.find(p=>p.actor.id===c.id),cd=combat.combatants.find(p=>p.actor.id===d.id);
  const req=(operation,options={},id)=>game.paranoia.combat.request(combat,operation,options,id);
  await set("surprise");await req("surprise",{surprisingIds:[ca.id]});check(stateOf(combat).phase==="surpriseResolution"&&!stateOf(combat).surprise.resolved,"Surprise state");
  let denied=false;try{await req("declare",{action:"attack",movement:"walk",weaponId:bWeapon.id,targetId:ca.id},cb.id);}catch(error){denied=error.message.includes("lado sorprendido");}check(denied,"Surprised attacker allowed");
  await req("declare",{action:"evade",movement:"walk"},cb.id);await req("declare",{action:"attack",movement:"walk",weaponId:weapon.id,targetId:cb.id},ca.id);const surprise=await req("attack",{weaponId:weapon.id,targetId:cb.id,messageMode:"gm"},ca.id);check(game.messages.get(surprise.messageId)?.getFlag(NS,"attack")?.modifiers.defenderEvading===-4,"Surprise defense roll");await req("next",{force:true});check(combat.round===1&&stateOf(combat).phase==="npcDecision"&&stateOf(combat).surprise.resolved,"Normal turn1 after surprise");
  await set("burstFire","range","cover","movement");await req("declare",{action:"burst",movement:"march",weaponId:weapon.id,targetIds:[cb.id,cc.id,cd.id]},ca.id);await req("declare",{action:"evade",movement:"run"},cb.id);await req("next",{force:true});await req("next",{force:true});
  const p=await req("preview",{weaponId:weapon.id,targetId:cb.id,burstCount:3,rangeBand:"medium",cover:"half"},ca.id);check(p.finalTarget===-11&&p.modifiers.range===-3&&p.modifiers.movement===-5,"Burst before range then cover/movement/evasion");
  const burst=await req("attack",{weaponId:weapon.id,targetId:cb.id,confirmBurstSeparation:true,targetCircumstances:{[cb.id]:{rangeBand:"medium",cover:"half"},[cc.id]:{rangeBand:"short",cover:"none"},[cd.id]:{rangeBand:"long",cover:"light"}},messageMode:"gm"},ca.id);
  const grouped=game.messages.get(burst.messageId);check(grouped.rolls.length===3&&grouped.getFlag(NS,"burstAttack").burstSkill===5,"Grouped burst rolls");check(ca.getFlag(NS,"attack").resolved,"Burst counts as one action");denied=false;try{await req("attack",{weaponId:weapon.id,targetId:cb.id,confirmBurstSeparation:true},ca.id);}catch{denied=true;}check(denied,"Burst repeated");
  await set("range","cover");const pp=await req("preview",{weaponId:weapon.id,targetId:cb.id,distanceMeters:4,cover:"light"},ca.id);check(pp.finalTarget===23,"Point blank multiplier minus cover and evasion");denied=false;try{await req("preview",{weaponId:weapon.id,targetId:cb.id,distanceMeters:51},ca.id);}catch{denied=true;}check(denied,"Beyond maximum allowed");
  await set("weaponHandling","ammunition");await weapon.update({"system.ammoCurrent":0});await req("next",{force:true});await req("next",{force:true});
  await req("declare",{action:"draw",movement:"run",weaponId:weapon.id},ca.id);await req("next",{force:true});await req("next",{force:true});await req("handling",{},ca.id);check(ca.getFlag(NS,"weaponReady").includes(weapon.id),"Drawing ready state");
  await req("next",{force:true});await req("next",{force:true});await req("declare",{action:"reload",movement:"none",weaponId:weapon.id},ca.id);await req("next",{force:true});await req("next",{force:true});await req("handling",{},ca.id);check(weapon.system.ammoCurrent===6&&ammo.system.quantity===1,"Charge consume and load");await req("handling",{},ca.id);check(ammo.system.quantity===1,"Duplicate reload");
  await set("ammunition","malfunctions","repairs");await recordShot(weapon,19);check(weapon.system.ammoCurrent===5&&!weapon.system.malfunctioned,"Normal die19");await recordShot(weapon,20);check(weapon.system.ammoCurrent===4&&weapon.system.malfunctioned,"Natural20 malfunction");await game.settings.set(NS,"specialRollResults",false);
  await repairWeapon(weapon,{prevent:true});check(weapon.system.malfunctioned,"Prevention repaired weapon");await repairWeapon(weapon);check(!weapon.system.malfunctioned,"Repair success");await weapon.update({"system.reliabilityType":"trulyExperimental","system.malfunctionThreshold":10,"system.malfunctioned":true});denied=false;try{await repairWeapon(weapon);}catch{denied=true;}check(denied,"Truly experimental normal repair");await repairWeapon(weapon,{override:true});check(!weapon.system.malfunctioned,"GM repair exception");
  await set("hitLocation","polyvalentArmor");await game.paranoia.HealthService.applyHealthResult(a,"wounded",{announce:false});await game.paranoia.HealthService.clearStun(a);await addWound(a,{location:"arm",side:"right",damageId:"live-arm"});check(a.system.health.status==="wounded","Localization replaced health");denied=false;try{await req("preview",{weaponId:weapon.id,targetId:cb.id},ca.id);}catch{denied=true;}check(denied,"Disabled arm weapon");await addWound(a,{location:"leg",damageId:"live-leg"});denied=false;try{await req("declare",{action:"move",movement:"run"},ca.id);}catch{denied=true;}check(denied,"Leg allows run");await req("declare",{action:"move",movement:"march"},ca.id);await addWound(a,{location:"head",consequence:"blind",permanent:true});await game.paranoia.HealthService.setStatus(a,"healthy");check(a.system.health.wounds.filter(w=>w.active).length===1&&a.system.health.wounds.at(-1).permanent,"Healing temporary vs permanent");
  check(armor.system.armorCode==="L4/B3/P2/PP6"&&armor.system.getProtectionFor("laser")===4&&armor.system.getProtectionFor("piercingProjectile")===6,"Poly armor model: "+JSON.stringify(armor.system.toObject()));await armor.sheet.render(true);check(armor.sheet.element.querySelector('[data-action="addProtection"]'),"Armor editor");await armor.sheet.close();await a.sheet.render(true);check(a.sheet.element.textContent.includes("Herida:"),"Wounds sheet");
  const oldArmor=new CONFIG.Item.dataModels.armor({protectionType:"laser",protectionValue:4},{strict:true});check(oldArmor.armorCode==="L4"&&oldArmor.protections.length===1,"Legacy armor migration");const oldWeapon=new CONFIG.Item.dataModels.weapon({experimental:true,charges:{value:3,max:6}},{strict:true});check(oldWeapon.reliabilityType==="experimental"&&oldWeapon.ammoCurrent===3,"Legacy weapon migration");
  await game.settings.set(NS,"useOptionalCombatRules",false);const off=await req("preview",{weaponId:weapon.id,targetId:cb.id,pointBlank:true,rangeBand:"long",cover:"nearTotal"},ca.id);check(off.modifiers.pointBlank===4&&!Object.hasOwn(off.modifiers,"cover")&&off.finalTarget===off.baseValue+Object.values(off.modifiers).reduce((n,v)=>n+v,0),"Optional off basic pointblank");
  await set("hitLocation");await game.paranoia.HealthService.applyHealthResult(d,"wounded",{announce:false});await addWound(d,{location:"leg",damageId:"escalation-one"});await game.paranoia.HealthService.applyHealthResult(d,"wounded",{announce:false});await addWound(d,{location:"arm",damageId:"escalation-two"});check(d.system.health.status==="incapacitated"&&d.system.health.wounds.length===2,"Localized wounds blocked health escalation");await game.paranoia.HealthService.applyHealthResult(d,"dead",{announce:false});await game.paranoia.CloneService.activateNextClone(d,{inventory:"keep",power:"keep",silent:true});check(d.system.health.wounds.length===0&&d.system.clones.history.at(-1).localizedWounds.length===2,"Clone physical reset / wound archive");
  await integratedChecks(b);
  await game.settings.set(NS,"useOptionalCombatRules",true);await game.settings.set(NS,"optionalCombat.range",true);await game.settings.set(NS,"optionalCombat.cover",true);await game.settings.set(NS,"optionalCombat.ammunition",true);await game.settings.set(NS,"optionalCombat.malfunctions",true);await game.settings.set(NS,"optionalCombat.repairs",true);
  await weapon.update({"system.reliabilityType":"normal","system.malfunctioned":false,"system.ammoCurrent":6});
  const [owner]=await User.createDocuments([{name:`OptionalOwner-${a.id}`,role:1}]);await a.update({ownership:{default:0,[owner.id]:3}});await req("declare",{action:"attack",movement:"walk",weaponId:weapon.id,targetId:cb.id},ca.id);await req("unlock");await req("release",{},ca.id);
  return {version:game.version,actorId:a.id,combatId:combat.id,combatantId:ca.id,targetId:cb.id,weaponId:weapon.id,armorId:armor.id,burstMessageId:burst.messageId,ownerName:owner.name,surprise:true,burst:true,range:true,cover:true,movement:true,draw:true,reload:true,malfunctions:true,repair:true,wounds:true,polyArmor:true,migration:true,optionalOff:true,integratedSalvos:true};
}
async function integratedChecks(target){
  const weapon=()=>({name:"Integrated optional test",type:"weapon",system:{integrated:true,weaponCategory:"laser",skill:"dexterity.laserWeapons",maxRangeMeters:50,ammoCurrent:2,ammunition:{capacity:2}}}),program={name:"Verified test laser program",type:"robotProgram",system:{skill:"dexterity.laserWeapons",level:14,storageMode:"resident",active:true}};
  for(const type of ["robot","vehicle"]){
    const actor=await Actor.create({name:`Optional ${type} salvo`,type,system:type==="robot"?{robot:{memory:{capacity:100}}}:{vehicle:{control:{electronicBrainAvailable:true,currentMode:"electronicBrain"},electronicBrain:{memory:{capacity:100}}}},items:[program,weapon(),weapon()]});
    const combat=await Combat.create({combatants:[{actorId:actor.id,name:actor.name},{actorId:target.id,name:target.name}]}),attacker=combat.combatants.find(c=>c.actor.id===actor.id),defender=combat.combatants.find(c=>c.actor.id===target.id),ids=actor.items.filter(i=>i.type==="weapon").map(i=>i.id),req=(op,opts={},id)=>game.paranoia.combat.request(combat,op,opts,id);
    await game.settings.set(NS,"useOptionalCombatRules",true);for(const key of ["range","ammunition","weaponHandling"])await game.settings.set(NS,`optionalCombat.${key}`,true);await game.settings.set(NS,"optionalCombat.hitLocation",false);
    await req("start");await req("declare",{action:"attack",movement:"walk",weaponId:ids[0],targetId:defender.id,integratedWeaponIds:ids,weaponOperators:Object.fromEntries(ids.map(id=>[id,"electronicBrain"]))},attacker.id);await req("next",{force:true});await req("next",{force:true});
    for(const id of ids)await req("attack",{weaponId:id,targetId:defender.id,rangeBand:"short",messageMode:"gm"},attacker.id);
    check(ids.every(id=>actor.items.get(id).system.ammoCurrent===1&&attacker.getFlag(NS,"attack").weapons[id].resolved),`${type} integrated salvo ammo / range`);await combat.delete();
  }
  for(const key of Object.keys(OPTIONAL_RULES))await game.settings.set(NS,`optionalCombat.${key}`,false);
}
export async function checkOptionalOwner({actorId,weaponId,combatId,combatantId,targetId}){
  const actor=game.actors.get(actorId),weapon=actor.items.get(weaponId),combat=game.combats.get(combatId);
  await weapon.update({"system.ammoCurrent":99});check(weapon.system.ammoCurrent===6,"Owner direct ammunition edit");
  await weapon.update({"system.malfunctioned":true});check(!weapon.system.malfunctioned,"Owner direct malfunction edit");
  await actor.update({"system.health.wounds":[]});check(actor.system.health.wounds.length===3,"Owner removed wound records");
  await game.paranoia.combat.request(combat,"declare",{action:"attack",movement:"walk",weaponId,targetId},combatantId);
  let denied=false;try{await game.paranoia.combat.request(combat,"setReady",{weaponIds:[weaponId]},combatantId);}catch{denied=true;}check(denied,"Owner GM ready override");
  return {ownerAmmoProtected:true,ownerWoundsProtected:true,coordinatedDeclaration:true};
}
