// Generated by scripts/build-localization-catalogue.mjs. Translation fingerprints only.
export const CATALOGUE_KEYS={
  "laser-pistol": {
    "name": "P2.Text.m1db1kpm",
    "system.description": "P2.Text.m1c6xmiv",
    "system.reloadInfo": "P2.Text.m5gmb1e",
    "system.specialRules": "P2.Text.m1x07reb"
  },
  "cone-rifle": {
    "name": "P2.Text.m1kqjqla",
    "system.description": "P2.Text.m16beofy",
    "system.ammunitionProfiles.0.label": "P2.Text.m142r3g3",
    "system.ammunitionProfiles.1.label": "P2.Text.mqhy5ti",
    "system.ammunitionProfiles.2.label": "P2.Text.m9kpmc4",
    "system.ammunitionProfiles.3.label": "P2.Text.m1egs8y",
    "system.ammunitionProfiles.4.label": "P2.Text.mxfcav3",
    "system.ammunitionProfiles.6.label": "P2.Text.m1wn985t",
    "system.ammunitionProfiles.7.label": "P2.Text.mszw4e",
    "system.ammunitionProfiles.8.label": "P2.Text.m9bb9dr"
  },
  "projectile-pistol": {
    "name": "P2.Text.mjoze1r",
    "system.description": "P2.Text.m1v6sch9",
    "system.ammunitionProfiles.0.label": "P2.Text.m142r3g3",
    "system.ammunitionProfiles.1.label": "P2.Text.mqhy5ti",
    "system.ammunitionProfiles.2.label": "P2.Text.m9kpmc4",
    "system.ammunitionProfiles.3.label": "P2.Text.mp2gosk",
    "system.ammunitionProfiles.4.label": "P2.Text.mxfcav3",
    "system.ammunitionProfiles.6.label": "P2.Text.m1wn985t",
    "system.ammunitionProfiles.7.label": "P2.Text.mszw4e",
    "system.ammunitionProfiles.8.label": "P2.Text.m9bb9dr"
  },
  "projectile-rifle": {
    "name": "P2.Text.mldvepo",
    "system.description": "P2.Text.m2xt776",
    "system.ammunitionProfiles.0.label": "P2.Text.m142r3g3",
    "system.ammunitionProfiles.1.label": "P2.Text.mqhy5ti",
    "system.ammunitionProfiles.2.label": "P2.Text.m9kpmc4",
    "system.ammunitionProfiles.3.label": "P2.Text.mp2gosk",
    "system.ammunitionProfiles.4.label": "P2.Text.mxfcav3",
    "system.ammunitionProfiles.6.label": "P2.Text.m1wn985t",
    "system.ammunitionProfiles.7.label": "P2.Text.mszw4e",
    "system.ammunitionProfiles.8.label": "P2.Text.m9bb9dr"
  },
  "sonic-weapon": {
    "name": "P2.Text.m1ldfigg",
    "system.description": "P2.Text.mj1wo0a",
    "system.specialRules": "P2.Text.mmkds83"
  },
  "ice-pistol": {
    "name": "P2.Text.muk3dv",
    "system.description": "P2.Text.megsqhw",
    "system.specialRules": "P2.Text.mkt7sfs"
  },
  "energy-ray-weapon": {
    "name": "P2.Text.m103rnbl",
    "system.description": "P2.Text.m1dw6jll",
    "system.specialRules": "P2.Text.m1hydtpz"
  },
  "energy-pistol": {
    "name": "P2.Text.m7bvbo4",
    "system.description": "P2.Text.mjaubjr"
  },
  "water-gun": {
    "name": "P2.Text.m1bvgdvq",
    "system.description": "P2.Text.mb8gjth",
    "system.specialRules": "P2.Text.m10pqp01"
  },
  "flameador": {
    "name": "P2.Text.m5yatdg",
    "system.description": "P2.Text.mf9zq64",
    "system.specialRules": "P2.Text.m1h1yqev"
  },
  "stunner": {
    "name": "P2.Text.m33ztvd",
    "system.description": "P2.Text.m17ujjd8",
    "system.specialRules": "P2.Text.maldnm5"
  },
  "web-launcher": {
    "name": "P2.Text.m19vr4zj",
    "system.description": "P2.Text.mdj8xy3",
    "system.specialRules": "P2.Text.my5lexv"
  },
  "flamethrower": {
    "name": "P2.Text.mvou6l3",
    "system.description": "P2.Text.m10my317",
    "system.specialRules": "P2.Text.m19gakfh"
  },
  "gauss-cannon": {
    "name": "P2.Text.m17whzj4",
    "system.description": "P2.Text.m1pwhaw9",
    "system.specialRules": "P2.Text.mb6xjdo"
  },
  "plasma-generator": {
    "name": "P2.Text.maa4vld",
    "system.description": "P2.Text.m7y10zw",
    "system.specialRules": "P2.Text.m18lb98d"
  },
  "grenade": {
    "name": "P2.Text.m1y2paql",
    "system.description": "P2.Text.mlh7l35",
    "system.specialRules": "P2.Text.moqlhs5"
  },
  "unarmed": {
    "name": "P2.Text.m16qusi1",
    "system.description": "P2.Text.mf2g5q0",
    "system.specialRules": "P2.Text.mmtxgts"
  },
  "brass-knuckles": {
    "name": "P2.Text.mbbe2gw",
    "system.description": "P2.Text.m8jusfj",
    "system.specialRules": "P2.Text.mw9t1qo"
  },
  "knife": {
    "name": "P2.Text.mnrbyam",
    "system.specialRules": "P2.Text.miojat9"
  },
  "mace": {
    "name": "P2.Text.mk1ynli",
    "system.specialRules": "P2.Text.ma99f80"
  },
  "sword": {
    "name": "P2.Text.m1h40php",
    "system.specialRules": "P2.Text.ma99f80"
  },
  "club": {
    "name": "P2.Text.m1cp50jb",
    "system.specialRules": "P2.Text.ma99f80"
  },
  "axe": {
    "name": "P2.Text.m1srgolc",
    "system.description": "P2.Text.m1l0hdyo"
  },
  "neural-whip": {
    "name": "P2.Text.m100zjhu",
    "system.description": "P2.Text.mp514ya",
    "system.specialRules": "P2.Text.m1hpiy4o"
  },
  "energy-sword": {
    "name": "P2.Text.m1mz0pbg",
    "system.description": "P2.Text.mtmj0dv",
    "system.specialRules": "P2.Text.mgfbges"
  },
  "laser-cannon-model-i": {
    "name": "P2.Text.m138nv3z",
    "system.reloadInfo": "P2.Text.mpraly3"
  },
  "laser-cannon-model-ii": {
    "name": "P2.Text.m6tpl8i",
    "system.reloadInfo": "P2.Text.m1n0whwx"
  },
  "laser-cannon-model-iii": {
    "name": "P2.Text.miyho7l",
    "system.specialRules": "P2.Text.m1aqh8sn"
  },
  "vehicle-sonic-projector": {
    "name": "P2.Text.mt895e6",
    "system.specialRules": "P2.Text.m105x3ic"
  },
  "tubular-cannon-model-i": {
    "name": "P2.Text.m1480rf1",
    "system.reloadInfo": "P2.Text.m652rtx",
    "system.description": "P2.Text.m1d1j4yu"
  },
  "tubular-cannon-model-ii": {
    "name": "P2.Text.m1fdc6oc",
    "system.reloadInfo": "P2.Text.m13att4o"
  },
  "vehicle-flamethrower": {
    "name": "P2.Text.m11oi2yl",
    "system.reloadInfo": "P2.Text.m9c1nrv",
    "system.description": "P2.Text.m177xswv"
  },
  "vehicle-missile-launcher": {
    "name": "P2.Text.m7rv63f",
    "system.reloadInfo": "P2.Text.mek1q6h",
    "system.specialRules": "P2.Text.m192wjgz"
  },
  "anti-missile-laser": {
    "name": "P2.Text.m180f4ei",
    "system.specialRules": "P2.Text.molrgbf"
  },
  "vehicle-gas-launcher": {
    "name": "P2.Text.m1sadwlw",
    "system.specialRules": "P2.Text.m10o7dbs"
  },
  "laser-rifle": {
    "name": "P2.Text.m1buwygg",
    "system.description": "P2.Text.m11ywpoe"
  },
  "sonic-rifle": {
    "name": "P2.Text.m8w3dji",
    "system.description": "P2.Text.m11ywpoe",
    "system.specialRules": "P2.Text.mmkds83"
  },
  "throwing-knife": {
    "name": "P2.Text.m125nj6n",
    "system.description": "P2.Text.m11ywpoe"
  },
  "bow": {
    "name": "P2.Text.mebxrwc",
    "system.description": "P2.Text.m11ywpoe"
  },
  "thrown-rock": {
    "name": "P2.Text.m1e0rf4y",
    "system.description": "P2.Text.m11ywpoe"
  },
  "spear": {
    "name": "P2.Text.m1cderm5",
    "system.description": "P2.Text.m11ywpoe",
    "system.specialRules": "P2.Text.m108hrhb"
  },
  "standard-troubleshooter-uniform": {
    "name": "P2.Text.mor5qnd",
    "system.description": "P2.Text.m17l7x12",
    "system.specialRules": "P2.Text.m4c7xjp"
  },
  "reflect-armor": {
    "name": "P2.Text.m98tsj4",
    "system.description": "P2.Text.m1bbb9gj",
    "system.specialRules": "P2.Text.m174ifja"
  },
  "insulating-suit": {
    "name": "P2.Text.maby71c",
    "system.description": "P2.Text.m17z7cpc"
  },
  "asbestos-suit": {
    "name": "P2.Text.m1vtpvut",
    "system.description": "P2.Text.m17z7cpc"
  },
  "combat-armor": {
    "name": "P2.Text.m1xyr36",
    "system.description": "P2.Text.m17z7cpc"
  },
  "plate-armor": {
    "name": "P2.Text.molce07",
    "system.description": "P2.Text.m17z7cpc"
  },
  "chainmail-armor": {
    "name": "P2.Text.medl7uq",
    "system.description": "P2.Text.m17z7cpc"
  },
  "leather-armor": {
    "name": "P2.Text.m1fmvkep",
    "system.description": "P2.Text.m17z7cpc"
  },
  "faraday-suit": {
    "name": "P2.Text.m1ar677l",
    "system.description": "P2.Text.m17z7cpc"
  },
  "kevlar-armor": {
    "name": "P2.Text.mc545n6",
    "system.description": "P2.Text.m17z7cpc"
  },
  "battle-suit": {
    "name": "P2.Text.m1kb21hb",
    "system.description": "P2.Text.m17z7cpc"
  },
  "laser-charge": {
    "name": "P2.Text.m1e523pn",
    "system.description": "P2.Text.m1rsglgq",
    "system.specialRules": "P2.Text.msu56do"
  },
  "refreshing-fizzy-beverage": {
    "name": "P2.Text.mld2ru3"
  },
  "happiness-energy-bar": {
    "name": "P2.Text.m1603u1i"
  },
  "megaphone": {
    "name": "P2.Text.m1m5vvfj"
  },
  "flashlight": {
    "name": "P2.Text.m189i5qq"
  },
  "lighter-knife": {
    "name": "P2.Text.mqsllom",
    "system.description": "P2.Text.m1svinf4"
  },
  "gas-mask": {
    "name": "P2.Text.mkw9m6p"
  },
  "superglue-with-solvent": {
    "name": "P2.Text.mrugwhb"
  },
  "infrared-goggles": {
    "name": "P2.Text.m15a3xer"
  },
  "smoke-detector-alarm": {
    "name": "P2.Text.m7s13cc"
  },
  "plasticord": {
    "name": "P2.Text.m26ih3a",
    "system.description": "P2.Text.mzxphs8"
  },
  "thermos": {
    "name": "P2.Text.m1ao7cy0"
  },
  "first-aid-kit": {
    "name": "P2.Text.m1lzu4o1"
  },
  "portrait-mado-n-nah-1": {
    "name": "P2.Text.m6erdr9",
    "system.description": "P2.Text.mxixkoa"
  },
  "cone-rifle-standard-bullets": {
    "name": "P2.Text.m18k196o",
    "system.description": "P2.Text.m1z0kod7"
  },
  "cone-rifle-dum-dum": {
    "name": "P2.Text.m12vtxt1",
    "system.description": "P2.Text.mmofpxa"
  },
  "cone-rifle-explosive-bullets": {
    "name": "P2.Text.mnbszyw",
    "system.description": "P2.Text.mv3tnln"
  },
  "armor-piercing-bullets": {
    "name": "P2.Text.myjw01f",
    "system.description": "P2.Text.mcco18a"
  },
  "flare-rounds": {
    "name": "P2.Text.moztwau",
    "system.description": "P2.Text.m8fcp5"
  },
  "hallucinogenic-gas-round": {
    "name": "P2.Text.m3pw1yi",
    "system.description": "P2.Text.mdcjem6",
    "system.specialRules": "P2.Text.m11wyww4"
  },
  "corrosive-gas-round": {
    "name": "P2.Text.m19e3aqa",
    "system.specialRules": "P2.Text.myhsb9g"
  },
  "gauss-gas-round": {
    "name": "P2.Text.mdhcba4",
    "system.description": "P2.Text.m5loycw",
    "system.specialRules": "P2.Text.m16c4vwb"
  },
  "emetic-gas-round": {
    "name": "P2.Text.m1x5yiy2",
    "system.specialRules": "P2.Text.m1hg8mf5"
  },
  "laughing-gas-round": {
    "name": "P2.Text.m1yy02os",
    "system.specialRules": "P2.Text.m3vfvjt"
  },
  "lethal-gas-round": {
    "name": "P2.Text.m1ickb76",
    "system.specialRules": "P2.Text.m1ij9ycz"
  },
  "viscous-gas-round": {
    "name": "P2.Text.m15ru8l8",
    "system.specialRules": "P2.Text.m18h9r44"
  },
  "smoke-round": {
    "name": "P2.Text.m1tzmdi2",
    "system.specialRules": "P2.Text.m17v3mls"
  },
  "anti-electronic-projectile": {
    "name": "P2.Text.m1ax7x4r",
    "system.description": "P2.Text.m1dk6ist"
  },
  "biochemical-projectile": {
    "name": "P2.Text.m4hvqrk",
    "system.specialRules": "P2.Text.m1xawak1"
  },
  "napalm-projectile": {
    "name": "P2.Text.m1wm5u7w",
    "system.specialRules": "P2.Text.m2v8mlt"
  },
  "explosive-at-projectile": {
    "name": "P2.Text.m1260i0i",
    "system.description": "P2.Text.m1s1ke7x"
  },
  "tactical-projectile": {
    "name": "P2.Text.m1a8goth",
    "system.description": "P2.Text.m1rcfcs5"
  },
  "contact-detonator": {
    "name": "P2.Text.mcdkyr3",
    "system.description": "P2.Text.mls62cb"
  },
  "gauss-detonator": {
    "name": "P2.Text.mwu002y",
    "system.description": "P2.Text.mmf98vu"
  },
  "remote-detonator": {
    "name": "P2.Text.m1ltiukt",
    "system.description": "P2.Text.m6y2saj"
  },
  "delayed-detonator": {
    "name": "P2.Text.msaqp65",
    "system.description": "P2.Text.m1ezkk12"
  },
  "thermal-detonator": {
    "name": "P2.Text.m19b6lhg",
    "system.description": "P2.Text.mnz9oxv"
  },
  "communicator": {
    "name": "P2.Text.mujfl59",
    "system.description": "P2.Text.ma0w722"
  },
  "multirecorder": {
    "name": "P2.Text.mmzd82n",
    "system.description": "P2.Text.mob1piw"
  },
  "vehicle-smoke-launcher": {
    "name": "P2.Text.m1groyi1",
    "system.specialRules": "P2.Text.m17lu86w"
  },
  "interference-emitter-a": {
    "name": "P2.Text.m1731fx4",
    "system.specialRules": "P2.Text.mc6jobi"
  },
  "interference-emitter-r": {
    "name": "P2.Text.m1cctw3l",
    "system.specialRules": "P2.Text.mnszw27"
  },
  "interference-emitter-gauss": {
    "name": "P2.Text.m2ekpx6",
    "system.specialRules": "P2.Text.mv39aiu"
  },
  "interference-emitter-t": {
    "name": "P2.Text.m1cwt3hj",
    "system.specialRules": "P2.Text.m1ihjbid"
  },
  "robodoctor": {
    "name": "P2.Text.m1xymt4e",
    "system.robot.description": "P2.Text.m8c2x8h"
  },
  "robodoctor-model-i": {
    "name": "P2.Text.mrwoywp",
    "system.robot.description": "P2.Text.m6nf8vv",
    "items.0.name": "P2.Text.m19vvic5"
  },
  "robodoctor-model-v": {
    "name": "P2.Text.myuf190",
    "system.robot.description": "P2.Text.m1ge7xrl",
    "items.0.name": "P2.Text.m1aztx41",
    "items.1.name": "P2.Text.mnno72w",
    "items.1.system.description": "P2.Text.m16jl5qu"
  },
  "robodoctor-model-xii": {
    "name": "P2.Text.mvunvm4",
    "system.robot.description": "P2.Text.m6nf8vv",
    "items.0.name": "P2.Text.m1xa3kmx"
  },
  "robomechanic": {
    "name": "P2.Text.mo1vb64",
    "system.robot.description": "P2.Text.ml7o0z6",
    "system.robot.movement.mode": "P2.Text.m1531glo",
    "items.0.name": "P2.Text.m9ishkf",
    "items.0.system.description": "P2.Text.m1vyyb5r",
    "items.1.name": "P2.Text.m1531glo",
    "items.1.system.description": "P2.Text.mnknp78",
    "items.2.name": "P2.Text.maexyeo",
    "items.2.system.description": "P2.Text.mgwtzcy"
  },
  "robomop": {
    "name": "P2.Text.m1r8japv",
    "system.robot.description": "P2.Text.m1lcmi6o",
    "items.0.name": "P2.Text.m122rvtf",
    "items.0.system.description": "P2.Text.m1ueoel5"
  },
  "robosoldier": {
    "name": "P2.Text.m1ca9q0r",
    "system.robot.description": "P2.Text.m1ixa6g"
  },
  "roboguard": {
    "name": "P2.Text.mh2xlk8",
    "system.robot.description": "P2.Text.m134eq9d"
  },
  "roboteacher": {
    "name": "P2.Text.meyczdf",
    "system.robot.description": "P2.Text.mhp9245"
  },
  "roboplane": {
    "name": "P2.Text.mv3keg8",
    "system.robot.description": "P2.Text.m1fcswwx"
  },
  "robopet": {
    "name": "P2.Text.m1rmgb4t",
    "system.robot.description": "P2.Text.meaoupe"
  },
  "roboclown": {
    "name": "P2.Text.m1u9og5a",
    "system.robot.description": "P2.Text.meaoupe"
  },
  "robocommunicator": {
    "name": "P2.Text.m195wbbl",
    "system.robot.description": "P2.Text.m1mcoanl"
  },
  "medicine-program-4": {
    "name": "P2.Text.m19vvic5"
  },
  "medicine-program-8": {
    "name": "P2.Text.m1aztx41"
  },
  "medicine-program-15": {
    "name": "P2.Text.m1xa3kmx"
  },
  "buitre-guerrero-920": {
    "name": "P2.Text.m12kfdqc",
    "system.vehicle.model": "P2.Text.moz0z4b",
    "system.vehicle.purpose": "P2.Text.m1h5e92u",
    "system.vehicle.description": "P2.Text.m1oiqk4q",
    "system.vehicle.design": "P2.Text.m110b7xq",
    "system.vehicle.electronicBrain.programmingNotes": "P2.Text.mxjzxsn",
    "system.vehicle.movement.description": "P2.Text.m1yezwm4",
    "system.vehicle.movement.modes.0.label": "P2.Text.m12duv12",
    "system.vehicle.movement.modes.0.notes": "P2.Text.m1st2ezt",
    "system.vehicle.specialRules": "P2.Text.mmbd1el",
    "system.vehicle.systems.0.name": "P2.Text.m1u1y4nq",
    "system.vehicle.systems.1.name": "P2.Text.m3rp3n2",
    "items.0.name": "P2.Text.m6tpl8i",
    "items.0.system.reloadInfo": "P2.Text.m1n0whwx",
    "items.1.name": "P2.Text.m6tpl8i",
    "items.1.system.reloadInfo": "P2.Text.m1n0whwx",
    "items.2.name": "P2.Text.m7rv63f",
    "items.2.system.reloadInfo": "P2.Text.mek1q6h",
    "items.2.system.specialRules": "P2.Text.m192wjgz",
    "items.3.name": "P2.Text.m7rv63f",
    "items.3.system.reloadInfo": "P2.Text.mek1q6h",
    "items.3.system.specialRules": "P2.Text.m192wjgz",
    "items.4.name": "P2.Text.m7rv63f",
    "items.4.system.reloadInfo": "P2.Text.mek1q6h",
    "items.4.system.specialRules": "P2.Text.m192wjgz",
    "items.5.name": "P2.Text.m7rv63f",
    "items.5.system.reloadInfo": "P2.Text.mek1q6h",
    "items.5.system.specialRules": "P2.Text.m192wjgz",
    "items.6.name": "P2.Text.m180f4ei",
    "items.6.system.specialRules": "P2.Text.m67pfex",
    "items.7.name": "P2.Text.m1groyi1",
    "items.7.system.specialRules": "P2.Text.m17lu86w",
    "items.8.name": "P2.Text.m1731fx4",
    "items.8.system.specialRules": "P2.Text.mc6jobi",
    "items.9.name": "P2.Text.m1cctw3l",
    "items.9.system.specialRules": "P2.Text.mnszw27",
    "items.10.name": "P2.Text.m2ekpx6",
    "items.10.system.specialRules": "P2.Text.mv39aiu",
    "items.11.name": "P2.Text.m1cwt3hj",
    "items.11.system.specialRules": "P2.Text.m1ihjbid",
    "items.12.name": "P2.Text.m8kllxk"
  },
  "robocoche-vtt-17": {
    "name": "P2.Text.m18psz05",
    "system.vehicle.model": "P2.Text.m10zecrh",
    "system.vehicle.purpose": "P2.Text.my6qkjk",
    "system.vehicle.description": "P2.Text.m12u70zl",
    "system.vehicle.movement.modes.0.label": "P2.Text.m3epd9c",
    "system.vehicle.movement.modes.0.terrain": "P2.Text.m585tjr",
    "system.vehicle.movement.modes.0.notes": "P2.Text.mv79tb0",
    "system.vehicle.movement.modes.1.label": "P2.Text.m25wfiv",
    "system.vehicle.movement.modes.1.terrain": "P2.Text.mhcdyvm",
    "system.vehicle.movement.modes.1.notes": "P2.Text.m1lq8g67",
    "system.vehicle.movement.modes.2.label": "P2.Text.m12duv12",
    "system.vehicle.movement.modes.2.notes": "P2.Text.mgpt3sd",
    "system.vehicle.flaws.0.name": "P2.Text.m16vh58z",
    "system.vehicle.flaws.0.description": "P2.Text.mop4itz",
    "system.vehicle.flaws.0.gmNotes": "P2.Text.mwsz1cy",
    "system.vehicle.specialRules": "P2.Text.mwo4obc"
  }
};
